### ISSUE TITLE
State diagram

### ISSUE THREAD

**Issue by g3force** [RoboCup-SSL/ssl-refbox#36]
Hi,
I created a state diagram some years ago for our team.
Maybe it is useful for others as well and could be included in the manual?

I attach it as png, but I can also provide it as eps. It was created with dia.

![referee-commands](https://cloud.githubusercontent.com/assets/779094/15112430/7ddca10e-15ee-11e6-8e51-fd379baec94b.png)

Cheers,
Nicolai
TIGERs Mannheim

**Comment by Hawk777** [comment]
I like it! Although, there are a few things I can think of that are missing:
* Halt and Force Start are shown in the same way (commands with no edges leading to them), yet they have different rules: Halt can be used literally any time at all, while Force Start can only be used during Stop.
* There is a transition from Halted to Timeout, which is the Resume Timeout button.
* The Cancel Timeout button provides an alternative transition from Timeout to Stopped.

Also, if we are going to publish this, perhaps you could also provide the original dia file which I can put in the repository so we can edit it later if needed?

**Comment by g3force** [comment]
You are right, somethings are not that accurate. I tried to apply your points to the diagram:
![referee-commands](https://cloud.githubusercontent.com/assets/779094/15453206/329781b8-200d-11e6-9597-e9f89b64c92f.png)

The timeout transitions make it a bit more complicated, and the problem is, that resume and cancel timeout are no commands in the protobuf message.

I found out, that I can attach zip files, so here is the dia file now as well:
[referee-commands.dia.zip](https://github.com/RoboCup-SSL/ssl-refbox/files/276230/referee-commands.dia.zip)
