### ISSUE TITLE
NORMAL_START signal can't be given from the PREPARE_KICKOFF_US state

### ISSUE THREAD

**Issue by emielsteerneman** [RoboCup-SSL/ssl-refbox#48]
In the 2016 release, "Normal Start" could be clicked after clicking "Kickoff". It seems that this should also be the case, looking at https://robocup-ssl.github.io/ssl-refbox/state-machine.png . In the current version, "Normal Start" is greyed out.

**Comment by g3force** [comment]
You have to set team names first.

**Comment by emielsteerneman** [comment]
Thanks, that worked
