### ISSUE TITLE
Installation page shows wrong procedure

### ISSUE THREAD

**Issue by ShotaAk** [RoboCup-SSL/ssl-refbox#50]
This page shows wrong installation.

https://robocup-ssl.github.io/ssl-refbox/install.html

1. sudo ./installDeps.sh
1. git clone https://github.com/RoboCup-SSL/ssl-refbox.git
1. cd ssl-refbox
1. make

Please fix to below procedure.

1. git clone https://github.com/RoboCup-SSL/ssl-refbox.git
1. cd ssl-refbox
1. sudo ./installDeps.sh
1. make

**Comment by g3force** [comment]
fixed.
