### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by RobotJente** [RoboCup-SSL/ssl-refbox#51]
It seems this repository has been replaced by https://github.com/RoboCup-SSL/ssl-game-controller. It was not clear (at least, not to me) from this repository that it is deprecated.

**Comment by g3force** [comment]
Good point, I've updated readme and repo description. Anything else to update?

**Comment by RobotJente** [comment]
Thank you for the quick response! There is nothing else that I have seen.
